server:
  http_listen_port: 9080  #Promtail listen port
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push  #Loki target instance

scrape_configs: #The most important part
  - job_name: system
    static_configs:
    - targets:
        - localhost #Promtail target is localhost
      labels:
        instance: fujiserver #Label identifier for instance (hostname -f)
        env: fujiserver #Environment label
        job: secure #Job label
        __path__: /var/log/auth.log
  # - job_name: docker
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 5s
  #       filters:
  #         - name: label
  #           values: ["logging=promtail"]
  #   relabel_configs:
  #     - source_labels: ['__meta_docker_container_name']
  #       regex: '/(.*)'
  #       target_label: 'container'
  #     - source_labels: ['__meta_docker_container_log_stream']
  #       target_label: 'logstream'
  #     - source_labels: ['__meta_docker_container_label_logging_jobname']
  #       target_label: 'job'