auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  storage:
    s3:
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      bucketnames: loki
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}
      s3forcepathstyle: true
      insecure: true
schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index: {prefix: index_, period: 24h}
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  aws:
    http_config:
      response_header_timeout: 30s
ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_encoding: snappy
compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: s3
  retention_delete_worker_count: 4
limits_config:
  retention_period: 720h
  ingestion_rate_mb: 2
  ingestion_burst_size_mb: 4
  reject_old_samples_max_age: 168h
  max_query_parallelism: 2
  split_queries_by_interval: 15m
  allow_structured_metadata: true
querier:
  max_concurrent: 2
analytics:
  reporting_enabled: false
